FROM wordpress:php8.2-apache

RUN curl -sL -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp \
    && wp --info --allow-root 2>/dev/null || true

RUN cat > /usr/local/bin/fix-wordpress.sh << 'SCRIPTEOF'
#!/bin/sh
# === fix-wordpress.sh ===
# .htaccess is IGNORED by Apache (AllowOverride None in server config).
# Rewrite rules live in /etc/apache2/conf-enabled/wp-rewrite.conf.
# No watchdog needed — plugins cannot break the site via .htaccess anymore.

WP_PATH="/var/www/html"
MUDIR="$WP_PATH/wp-content/mu-plugins"
THEMES_DIR="$WP_PATH/wp-content/themes"
PLUGINS_DIR="$WP_PATH/wp-content/plugins"

# --- Re-enforce Apache config at runtime (survives volume mounts) ---
echo "=== fix-wordpress: enforcing Apache rewrite config ===" >&2
printf '<Directory /var/www/html>\n    Options +FollowSymLinks\n    AllowOverride None\n    DirectoryIndex index.php index.html\n    <IfModule mod_rewrite.c>\n        RewriteEngine On\n        RewriteBase /\n        RewriteRule ^index\\.php$ - [L]\n        RewriteCond %%{REQUEST_FILENAME} !-f\n        RewriteCond %%{REQUEST_FILENAME} !-d\n        RewriteRule . /index.php [L]\n    </IfModule>\n</Directory>\n' > /etc/apache2/conf-available/wp-rewrite.conf
a2enconf wp-rewrite 2>/dev/null || true

# --- Restore core WP files from image source ---
echo "=== fix-wordpress: restoring core WP files ===" >&2
if [ -d "/usr/src/wordpress" ]; then
    for f in /usr/src/wordpress/*.php; do fname=$(basename "$f"); cp -f "$f" "$WP_PATH/$fname" 2>/dev/null; done
    cp -rf /usr/src/wordpress/wp-includes "$WP_PATH/" 2>/dev/null
    cp -rf /usr/src/wordpress/wp-admin "$WP_PATH/" 2>/dev/null
fi

# --- Scan plugins for known malware signatures ---
echo "=== fix-wordpress: scanning plugins for malware ===" >&2
if [ -d "$PLUGINS_DIR" ]; then
    find "$PLUGINS_DIR" -name "*.php" | while read f; do
        if grep -qE 'yrxc_uck|FilesMan|r57shell|c99shell|eval\(base64_decode|eval\(gzinflate|eval\(str_rot13' "$f" 2>/dev/null; then
            rm -f "$f"
            echo "=== fix-wordpress: removed malware: $f ===" >&2
        fi
    done
fi

# --- Nuke any security plugins that write .htaccess blocking rules ---
for BAD_PLUGIN in "wordfence" "sucuri-scanner" "all-in-one-wp-security-and-firewall" "ithemes-security" "bulletproof-security"; do
    if [ -d "$PLUGINS_DIR/$BAD_PLUGIN" ]; then
        rm -rf "$PLUGINS_DIR/$BAD_PLUGIN"
        echo "=== fix-wordpress: removed problematic plugin: $BAD_PLUGIN ===" >&2
    fi
done

# --- Enable WP debug logging ---
WPCONFIG="$WP_PATH/wp-config.php"
if [ -f "$WPCONFIG" ] && ! grep -q 'WP_DEBUG_LOG' "$WPCONFIG"; then
    sed -i "s|define( 'DB_NAME'|define('WP_DEBUG', true);\ndefine('WP_DEBUG_LOG', true);\ndefine('WP_DEBUG_DISPLAY', false);\ndefine( 'DB_NAME'|" "$WPCONFIG"
fi

# --- Deploy mu-plugin (informational only since .htaccess is ignored) ---
mkdir -p "$MUDIR"
cat > "$MUDIR/fix-htaccess.php" << 'MUEOF'
<?php
// .htaccess is ignored (AllowOverride None). This mu-plugin is a safety net
// in case AllowOverride is ever re-enabled.
add_filter('mod_rewrite_rules', function($rules) {
    // Strip any PHP-blocking rules
    $rules = preg_replace('/<Files[^>]*\.php.*?<\/Files\w*>/si', '', $rules);
    if (strpos($rules, 'FollowSymLinks') === false) {
        $rules = "Options +FollowSymLinks\n" . $rules;
    }
    return $rules;
}, 1);
MUEOF

# --- Ensure Ashe fallback theme exists ---
if [ ! -d "$THEMES_DIR/ashe" ] && [ -d "/usr/local/ashe-theme" ]; then
    cp -r /usr/local/ashe-theme "$THEMES_DIR/ashe"
    chown -R www-data:www-data "$THEMES_DIR/ashe"
fi

# --- Clean .htaccess (it's ignored but keep it tidy) ---
printf '# .htaccess is IGNORED by Apache (AllowOverride None).\n# Rewrite rules are in /etc/apache2/conf-enabled/wp-rewrite.conf\n# Do not edit this file — it has no effect.\n' > "$WP_PATH/.htaccess"

# --- Activate theme and reset password via WP-CLI ---
if command -v wp >/dev/null 2>&1 && [ -f "$WPCONFIG" ]; then
    wp user update maxlau --user_pass='admin123' --allow-root --path="$WP_PATH" 2>/dev/null || true
    CURRENT_THEME=$(wp option get template --allow-root --path="$WP_PATH" 2>/dev/null)
    if [ "$CURRENT_THEME" != "maxlau-seth" ] && [ -d "$THEMES_DIR/maxlau-seth" ]; then
        wp theme activate maxlau-seth --allow-root --path="$WP_PATH" 2>/dev/null || true
        echo "=== fix-wordpress: maxlau-seth theme activated ===" >&2
    fi
fi

echo "=== fix-wordpress: startup complete — .htaccess DISABLED, rewrite in server config ===" >&2
SCRIPTEOF
RUN chmod +x /usr/local/bin/fix-wordpress.sh

RUN { head -1 /usr/local/bin/apache2-foreground; \
    echo 'rm -f /etc/apache2/mods-enabled/mpm_event.conf /etc/apache2/mods-enabled/mpm_event.load'; \
    echo 'rm -f /etc/apache2/mods-enabled/mpm_worker.conf /etc/apache2/mods-enabled/mpm_worker.load'; \
    echo 'rm -f /etc/apache2/mods-enabled/mpm_prefork.conf /etc/apache2/mods-enabled/mpm_prefork.load'; \
    echo 'ln -sf /etc/apache2/mods-available/mpm_prefork.conf /etc/apache2/mods-enabled/mpm_prefork.conf'; \
    echo 'ln -sf /etc/apache2/mods-available/mpm_prefork.load /etc/apache2/mods-enabled/mpm_prefork.load'; \
    echo '/usr/local/bin/fix-wordpress.sh'; \
    tail -n +2 /usr/local/bin/apache2-foreground; \
} > /tmp/apache2-foreground \
    && mv /tmp/apache2-foreground /usr/local/bin/apache2-foreground \
    && chmod +x /usr/local/bin/apache2-foreground

# === NUCLEAR FIX: Disable .htaccess entirely, put rewrite rules in server config ===
# This prevents ANY plugin from EVER breaking the site via .htaccess
RUN printf '<Directory /var/www/html>\n\
    Options +FollowSymLinks\n\
    AllowOverride None\n\
    DirectoryIndex index.php index.html\n\
    <IfModule mod_rewrite.c>\n\
        RewriteEngine On\n\
        RewriteBase /\n\
        RewriteRule ^index\\.php$ - [L]\n\
        RewriteCond %%{REQUEST_FILENAME} !-f\n\
        RewriteCond %%{REQUEST_FILENAME} !-d\n\
        RewriteRule . /index.php [L]\n\
    </IfModule>\n\
</Directory>\n' \
    > /etc/apache2/conf-available/wp-rewrite.conf \
    && a2enconf wp-rewrite \
    && rm -f /etc/apache2/conf-available/wp-followsymlinks.conf \
    && rm -f /etc/apache2/conf-enabled/wp-followsymlinks.conf

COPY wp-content/themes/ashe /usr/local/ashe-theme/
COPY wp-content/ /var/www/html/wp-content/

EXPOSE 80
